CREATE TABLE USERS
(
    USERNAME VARCHAR(50) PRIMARY KEY,
    FIRSTNAME VARCHAR(40) NOT NULL,
    LASTNAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL UNIQUE,
    DOB DATE,
    PASSWORD VARCHAR(30) NOT NULL,  
    PROFILE_PHOTO VARCHAR(250) 
);
CREATE TABLE LOCATION
(
    ID VARCHAR(50) PRIMARY KEY,
    NAME VARCHAR(150) NOT NULL
);
CREATE TABLE RATE_MEDIA 
(
    USERNAME VARCHAR(50) NOT NULL,
    MEDIA_ID VARCHAR(50) NOT NULL,
    RATING INTEGER CHECK ( (RATING>=0) AND (RATING<=5)  ),
    COMMENTS VARCHAR(300),
    PRIMARY KEY(USERNAME, MEDIA_ID),
    FOREIGN KEY(USERNAME) REFERENCES USERS(USERNAME) ,
    FOREIGN KEY(MEDIA_ID) REFERENCES MEDIA(ID)
);